# Site settings
title: Alex Bigelow
email: abigelow@cs.utah.edu
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://alex-r-bigelow.github.io" # the base hostname & protocol for your site
twitter_username: accidental_PhD
github_username:  alex-r-bigelow
facebook_username: alex-r-bigelow

# Build settings
markdown: kramdown

gems:
- jekyll-gist

highlighter: pygments

collections:
- publications
- experience