#!/bin/bash
#
# A hook that updates sitemap.xml and pages.json with the latest modification dates before committing

echo '<?xml version="1.0" encoding="UTF-8"?>' > sitemap.xml
echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> sitemap.xml

echo '[' > pages.json

urls=('' 'cv.html' 'blog.html' '404.html')
redirects=()

git ls-tree -r --name-only HEAD | ( while read filename; do
  if [[ -e $filename && ("$filename" =~ projects/.*/.*.html || "$filename" =~ blog/.*/.*.html) ]]; then
    urls+=("$filename")
  fi

  if [[ -e $filename && "$filename" =~ projects/.*/redirect.url ]]; then
    echo $filename
    redirects+=("$filename")
  fi
done

for url in "${urls[@]}"; do
  lastmod="$(git log -1 --date=format:%Y-%m-%d --format="%ad" -- $url)"
  echo "  <url>" >> sitemap.xml
  echo "    <lastmod>$lastmod</lastmod>" >> sitemap.xml
  echo "    <loc>https://alex-r-bigelow.github.io/$url</loc>" >> sitemap.xml
  echo "  </url>" >> sitemap.xml

  echo "  {" >> pages.json
  echo "    \"lastmod\":\"$lastmod\"," >> pages.json
  echo "    \"url\":\"https://alex-r-bigelow.github.io/$url\"" >> pages.json
  echo "  }," >> pages.json
done

for redirect in "${redirects[@]}"; do
  url=`cat $redirect`
  echo "  {" >> pages.json
  echo "    \"url\":\"$url\"" >> pages.json
  echo "  }," >> pages.json
done

echo '</urlset>' >> sitemap.xml

sed -i '$ s/.$//' pages.json
echo "]" >> pages.json

echo 'sitemap.xml and pages.json updated')
